# -*- coding: utf-8 -*-
"""2string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15bn_V26KYee3EEp4i3WdspkVgqBQ_vtt
"""

txt = "Merry Christmas"
# 2.1.1 print the length of the string
# TODO: Write your code below
len(txt)

# 2.1.2 Print the first character of the string txt.
# TODO: Write your code below
txt[0]

# 2.1.3 Get the characters from index 1 to index 3 (err).
# TODO: Write your code below
txt[1:4]

# 2.1.4 Convert the value of txt to upper case and print it.
# TODO: Write your code below
txt.upper()

# 2.1.5 Convert the value of txt to lower case and print it.
# TODO: Write your code below
txt.lower()

# 2.1.6 Return the string without any whitespace at the beginning or the end.
x = " Hello World "
# TODO: Write your code below
x.strip()

# 2.1.7 Replace the character H with a J and print the result
y = "Hello"
# TODO: Write your code below
y.replace("H","J")

# 2.1.8 Insert the correct syntax to add a placeholder for the name parameter.
# TODO: Update the code below
name = 'John'
txt = "My name is {}"
print(txt.format(name))