# -*- coding: utf-8 -*-
"""3operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soUrqZCFbOec8curBH6hHqE11yDqaWNR
"""

# 3.1.1 Multiply 4 with 8, and print the result.
# TODO: Write your code below
print(4*8)

x = 4
y = 8
print(x*y)

# 3.1.2 Divide 30 by 6, and print the result.
# TODO: Write your code below
print(30/6)