# -*- coding: utf-8 -*-
"""8pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwNLsvgsq3GfILYxpWlT85J8TG-0hs-t

# 13 Pandas
# reference: https://www.w3schools.com/python/pandas/default.asp
# reference: https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
"""

#import packages
import pandas as pd
import matplotlib.pyplot as plt

# 8.1 import the csv file Credit.csv into a pandas dataframe Credit using the read_csv() function in the pandas package
# TODO: Write your code below
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('Credit.csv')
print(df.to_string())

# 8.2 print the top 10 rows in Credit using the head() function of pandas
# TODO: Write your code below
df.head(10)

# 8.3 print information about Credit using the info() function of pandas.
# TODO: Write your code below
df.info(verbose=True)

# 8.4 using the shape attribute of pandas, print the number of rows and columns in Credit
# HINT: https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
# TODO: Write your code below
df.shape

# 8.5 if any, drop rows with missing values from the Credit dataframe
# TODO: Write your code below
df.empty

# 8.6 Calculate correlation coefficients between the numeric columns in Credit using the corr() function in pandas
# TODO: Write your code below
df.corr(method='pearson')

df.corr(min_periods=20)

df.corr()

# 8.7 Grouped by student, calculate the sum of Balance and average of Balance
# HINT: https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
# TODO: Write your code below
df.groupby(by='Student').agg(Balance_total=('Balance','sum'),avg_Balance=('Balance','mean'))

# 8.8 Using the plot() function in pandas, plot a histogram of Balance
# HINT: https://www.w3schools.com/python/pandas/pandas_plotting.asp
# TODO: Write your code below
df.plot.hist(y='Balance')

# 8.9 Using the plot() function in pandas, draw a scatterplot of Income vs. Balance
# HINT: https://www.w3schools.com/python/pandas/pandas_plotting.asp
# TODO: Write your code below
df.plot.scatter(x='Income',y='Balance')